export const TOKEN = "TOKEN";

export const MENU = ["React-", "Libery-", "Utils", "Nextjs-", "NodeJS-"];

// export const MENU = [
//   "Typescript-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "Nextjs-",
//   "NodeJS-",
//   "Libery-",
// ];
