export const TOKEN = "TOKEN";

export const MENU = ["Typescript-", "React-", "Nextjs-", "NodeJS-", "Libery-"];

// export const MENU = [
//   "Typescript-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "React-",
//   "Nextjs-",
//   "NodeJS-",
//   "Libery-",
// ];
